### ISSUE TITLE
Highlighting for syntax errors/warnings?

### ISSUE THREAD

**Issue by maartenba** [sleiphur/CodeMiniMap#3]
Highlighting for syntax errors/warnings would make it easy to recognize lines that have errors (or warnings).

(from discussion at https://twitter.com/KodzillaR/status/1319361325106106368)

**Comment by sleiphur** [comment]
pls see [CMM 1.6.7](https://github.com/sleiphur/CodeMiniMap/releases/tag/1.6.7).
