### ISSUE TITLE
Doesn't work in CLion 2020.2.4

### ISSUE THREAD

**Issue by avemilia** [sleiphur/CodeMiniMap#4]
Nothing shows up after install, changing settings makes no difference, toggling via shortcut does not produce any visual change. Perhaps you need some logs?

**Comment by sleiphur** [comment]
Maybe try this: In Code Minimap setting page, uncheck the 'Disabled' checkbox.

**Comment by avemilia** [comment]
It wasn't checked in, but turning it on and off doesn't produce any visual difference. The plugin seems to be no-op disabled regardless of the settings.

**Comment by sleiphur** [comment]
![image](https://user-images.githubusercontent.com/32027461/97645589-504c8a80-1a88-11eb-8ccb-52bbf5d08376.png)
Tested 1.6.5 on CLion 2020.2.4, it works.
Try to restart the CLion IDE or unload and reinstall the CMM plugin.

**Comment by avemilia** [comment]
Restart helped, thanks. Usually these days IDE doesn't need to restart on every single plugin install/uninstall as it was earlier, so I was relying on that. Oh well.
